# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'citas.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.fecha_c = QtWidgets.QLabel(Dialog)
        self.fecha_c.setGeometry(QtCore.QRect(30, 30, 47, 13))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.fecha_c.setFont(font)
        self.fecha_c.setObjectName("fecha_c")
        self.hora_c = QtWidgets.QLabel(Dialog)
        self.hora_c.setGeometry(QtCore.QRect(160, 30, 47, 13))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(11)
        self.hora_c.setFont(font)
        self.hora_c.setObjectName("hora_c")
        self.descripcion_c = QtWidgets.QLabel(Dialog)
        self.descripcion_c.setGeometry(QtCore.QRect(280, 30, 91, 21))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(11)
        self.descripcion_c.setFont(font)
        self.descripcion_c.setObjectName("descripcion_c")
        self.fecha_cita = QtWidgets.QDateEdit(Dialog)
        self.fecha_cita.setGeometry(QtCore.QRect(10, 50, 110, 22))
        self.fecha_cita.setObjectName("fecha_cita")
        self.tiempo_cita = QtWidgets.QTimeEdit(Dialog)
        self.tiempo_cita.setGeometry(QtCore.QRect(130, 50, 118, 22))
        self.tiempo_cita.setObjectName("tiempo_cita")
        self.texto_descripcion = QtWidgets.QTextEdit(Dialog)
        self.texto_descripcion.setGeometry(QtCore.QRect(270, 50, 111, 51))
        self.texto_descripcion.setObjectName("texto_descripcion")
        self.pushButton_guardar_cita = QtWidgets.QPushButton(Dialog)
        self.pushButton_guardar_cita.setGeometry(QtCore.QRect(70, 150, 75, 23))
        self.pushButton_guardar_cita.setObjectName("pushButton_guardar_cita")
        self.pushButton_cancelar_cita = QtWidgets.QPushButton(Dialog)
        self.pushButton_cancelar_cita.setGeometry(QtCore.QRect(190, 150, 75, 23))
        self.pushButton_cancelar_cita.setObjectName("pushButton_cancelar_cita")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.fecha_c.setText(_translate("Dialog", "Fecha"))
        self.hora_c.setText(_translate("Dialog", "Hora"))
        self.descripcion_c.setText(_translate("Dialog", "Descripcion"))
        self.pushButton_guardar_cita.setText(_translate("Dialog", "Guardar"))
        self.pushButton_cancelar_cita.setText(_translate("Dialog", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
