# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.email = QtWidgets.QLabel(self.centralwidget)
        self.email.setGeometry(QtCore.QRect(30, 70, 71, 21))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(11)
        self.email.setFont(font)
        self.email.setObjectName("email")
        self.contrasea = QtWidgets.QLabel(self.centralwidget)
        self.contrasea.setGeometry(QtCore.QRect(30, 100, 91, 21))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(11)
        self.contrasea.setFont(font)
        self.contrasea.setObjectName("contrasea")
        self.rol = QtWidgets.QLabel(self.centralwidget)
        self.rol.setGeometry(QtCore.QRect(30, 140, 47, 13))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(11)
        self.rol.setFont(font)
        self.rol.setObjectName("rol")
        self.lineEdit_nombre = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nombre.setGeometry(QtCore.QRect(140, 70, 113, 20))
        self.lineEdit_nombre.setObjectName("lineEdit_nombre")
        self.lineEdit_email = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_email.setGeometry(QtCore.QRect(140, 70, 113, 20))
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.lineEdit_contrasena = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_contrasena.setGeometry(QtCore.QRect(140, 100, 113, 20))
        self.lineEdit_contrasena.setObjectName("lineEdit_contrasena")
        self.radioButton_medico = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_medico.setGeometry(QtCore.QRect(140, 140, 82, 17))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(9)
        self.radioButton_medico.setFont(font)
        self.radioButton_medico.setObjectName("radioButton_medico")
        self.radioButton_paciente = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_paciente.setGeometry(QtCore.QRect(230, 140, 82, 17))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(9)
        self.radioButton_paciente.setFont(font)
        self.radioButton_paciente.setObjectName("radioButton_paciente")
        self.pushButton_iniciarSesion = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_iniciarSesion.setGeometry(QtCore.QRect(24, 180, 81, 23))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Demi")
        font.setPointSize(9)
        self.pushButton_iniciarSesion.setFont(font)
        self.pushButton_iniciarSesion.setObjectName("pushButton_iniciarSesion")
        self.pushButton_registrar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_registrar.setGeometry(QtCore.QRect(230, 180, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Demi")
        font.setPointSize(9)
        self.pushButton_registrar.setFont(font)
        self.pushButton_registrar.setObjectName("pushButton_registrar")
        self.nombre = QtWidgets.QLabel(self.centralwidget)
        self.nombre.setGeometry(QtCore.QRect(30, 40, 61, 16))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(11)
        self.nombre.setFont(font)
        self.nombre.setObjectName("nombre")
        self.lineEdit_nombre = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nombre.setGeometry(QtCore.QRect(140, 40, 113, 20))
        self.lineEdit_nombre.setObjectName("lineEdit_nombre")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.email.setText(_translate("MainWindow", "Email"))
        self.contrasea.setText(_translate("MainWindow", "Contraseña"))
        self.rol.setText(_translate("MainWindow", "Rol"))
        self.radioButton_medico.setText(_translate("MainWindow", "Medico"))
        self.radioButton_paciente.setText(_translate("MainWindow", "Paciente"))
        self.pushButton_iniciarSesion.setText(_translate("MainWindow", "Iniciar sesion"))
        self.pushButton_registrar.setText(_translate("MainWindow", "Registrar"))
        self.nombre.setText(_translate("MainWindow", "Nombre"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
#txtNombre