# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'panel_principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 401, 451))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tablaResumen = QtWidgets.QTableWidget(self.tab_3)
        self.tablaResumen.setGeometry(QtCore.QRect(20, 40, 341, 281))
        self.tablaResumen.setObjectName("tablaResumen")
        self.tablaResumen.setColumnCount(0)
        self.tablaResumen.setRowCount(0)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tablaPacientes = QtWidgets.QTableWidget(self.tab_4)
        self.tablaPacientes.setGeometry(QtCore.QRect(10, 40, 311, 171))
        self.tablaPacientes.setObjectName("tablaPacientes")
        self.tablaPacientes.setColumnCount(0)
        self.tablaPacientes.setRowCount(0)
        self.pushButton_editar = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_editar.setGeometry(QtCore.QRect(10, 250, 75, 23))
        self.pushButton_editar.setObjectName("pushButton_editar")
        self.pushButton_eliminar = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_eliminar.setGeometry(QtCore.QRect(230, 250, 75, 23))
        self.pushButton_eliminar.setObjectName("pushButton_eliminar")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.calendario_citas = QtWidgets.QCalendarWidget(self.tab_5)
        self.calendario_citas.setGeometry(QtCore.QRect(0, 0, 321, 191))
        self.calendario_citas.setObjectName("calendario_citas")
        self.lista_citas = QtWidgets.QListWidget(self.tab_5)
        self.lista_citas.setGeometry(QtCore.QRect(10, 210, 256, 192))
        self.lista_citas.setObjectName("lista_citas")
        self.tabWidget.addTab(self.tab_5, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Tab 1"))
        self.pushButton_editar.setText(_translate("MainWindow", "Editar"))
        self.pushButton_eliminar.setText(_translate("MainWindow", "Eliminar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Tab 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Página"))
